version: '3'

services:
  emqx:
    image: emqx:5.6.1
    container_name: emqx
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
    ports:
      - 1884:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    # volumes:
    #   - $PWD/emqx1_data:/opt/emqx/data

#
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto 
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      #- ./mosquitto/data:/mosquitto/data
      #- ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      #- 8883:8883
      - 9001:9001
    networks:
      - mosquitto-bridge


networks:
  emqx-bridge:
    driver: bridge
  mosquitto-bridge:
    #name: mosquitto_net
    driver: bridge